[package]
name = "rv_unit"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv-rt = "0.14.0"
riscv = "0.13.0"
semihosting = { version = "0.1.19", features = ["stdio"] }

[lib]
test = false
harness = false



