[build]
target = ["riscv64gc-unknown-none-elf"]

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -machine virt -serial mon:stdio -nographic -bios "
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x"
]
